// Automatically generated by MockGen. DO NOT EDIT!
// Source: client/iam/client.go

package iam

import (
	iam "github.com/aws/aws-sdk-go/service/iam"
	gomock "github.com/golang/mock/gomock"
)

// Mock of Client interface
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *_MockClientRecorder
}

// Recorder for MockClient (not exported)
type _MockClientRecorder struct {
	mock *MockClient
}

func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &_MockClientRecorder{mock}
	return mock
}

func (_m *MockClient) EXPECT() *_MockClientRecorder {
	return _m.recorder
}

func (_m *MockClient) CreateRole(name string) (*iam.Role, error) {
	ret := _m.ctrl.Call(_m, "CreateRole", name)
	ret0, _ := ret[0].(*iam.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockClientRecorder) CreateRole(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "CreateRole", arg0)
}

func (_m *MockClient) DeleteRole(name string) error {
	ret := _m.ctrl.Call(_m, "DeleteRole", name)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockClientRecorder) DeleteRole(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DeleteRole", arg0)
}

func (_m *MockClient) CreateInstanceProfile(name string) (*iam.InstanceProfile, error) {
	ret := _m.ctrl.Call(_m, "CreateInstanceProfile", name)
	ret0, _ := ret[0].(*iam.InstanceProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockClientRecorder) CreateInstanceProfile(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "CreateInstanceProfile", arg0)
}

func (_m *MockClient) DeleteInstanceProfile(name string) error {
	ret := _m.ctrl.Call(_m, "DeleteInstanceProfile", name)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockClientRecorder) DeleteInstanceProfile(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DeleteInstanceProfile", arg0)
}

func (_m *MockClient) AddRoleToInstanceProfile(instanceProfileName string, roleName string) error {
	ret := _m.ctrl.Call(_m, "AddRoleToInstanceProfile", instanceProfileName, roleName)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockClientRecorder) AddRoleToInstanceProfile(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "AddRoleToInstanceProfile", arg0, arg1)
}

func (_m *MockClient) CreatePolicy(name string, policy string) (*iam.Policy, error) {
	ret := _m.ctrl.Call(_m, "CreatePolicy", name, policy)
	ret0, _ := ret[0].(*iam.Policy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockClientRecorder) CreatePolicy(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "CreatePolicy", arg0, arg1)
}

func (_m *MockClient) DeletePolicy(name string) error {
	ret := _m.ctrl.Call(_m, "DeletePolicy", name)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockClientRecorder) DeletePolicy(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DeletePolicy", arg0)
}
